function HandleError(error)
ME = MXException(error);
throw(ME);
end